# Generated by Django 5.0.4 on 2024-04-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_pricelist_price_alter_storebalance_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='swope',
        ),
        migrations.CreateModel(
            name='SwopeStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store1', to='store.store')),
                ('store2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store2', to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
