# Generated by Django 5.0.4 on 2024-04-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_swope_delete_swopestore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='swope',
        ),
        migrations.AddField(
            model_name='store',
            name='swope',
            field=models.ManyToManyField(blank=True, null=True, to='store.store'),
        ),
    ]
