# Generated by Django 5.0.4 on 2024-04-09 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_store_swope_store_swope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='swope',
        ),
        migrations.CreateModel(
            name='SwopeStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_store_swope', to='store.store')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_store_swope', to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
