# Generated by Django 5.0.4 on 2024-04-09 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_store_swope_swopestore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreProduct',
        ),
    ]
