# Generated by Django 5.0.4 on 2024-04-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_storeproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SwopeHistory',
        ),
    ]
