# Generated by Django 4.1.5 on 2024-05-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_swopehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='type',
            field=models.IntegerField(choices=[(0, '----'), (1, 'Процент'), (2, 'Сумма')], default=0),
        ),
    ]
