# Generated by Django 4.1.5 on 2024-05-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
