# Generated by Django 4.1.5 on 2024-05-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_pricelist_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sell_price',
            field=models.BooleanField(default=False),
        ),
    ]
