# Generated by Django 4.1.5 on 2024-07-10 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_brand_slug'),
        ('store', '0012_storebalance_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='category',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='memory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='ram',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.region'),
        ),
    ]
