# Generated by Django 4.1.5 on 2024-07-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_pricelist_brand_remove_pricelist_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebalance',
            name='category',
            field=models.IntegerField(choices=[(0, 'Другой'), (1, 'Продажа'), (2, 'Прием'), (3, 'Рассрочка')], default=0),
        ),
    ]
