# Generated by Django 4.1.5 on 2024-07-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_storebalance_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebalance',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
