# Generated by Django 5.0.4 on 2024-04-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('surname', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number1', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number2', models.CharField(blank=True, max_length=30, null=True)),
                ('passport_file', models.URLField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'client',
                'ordering': ['-id'],
            },
        ),
    ]
