# Generated by Django 5.0.4 on 2024-05-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('messages', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
                'db_table': 'logs',
            },
        ),
    ]
