# Generated by Django 5.0.4 on 2024-05-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
