# Generated by Django 5.0.4 on 2024-05-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_barcode_client_tab_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tab_number',
            field=models.BigIntegerField(),
        ),
    ]
