# Generated by Django 5.0.4 on 2024-05-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_client_tab_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
