# Generated by Django 4.1.5 on 2024-07-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_discount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountlevel',
            name='discount_percentage_installment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
