# Generated by Django 4.1.5 on 2024-07-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_discountlevel_discount_percentage_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
