# Generated by Django 4.1.5 on 2024-07-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(1, 'Активный клиент'), (2, 'Надежный клиент'), (3, 'Ненадежный клиент')], default=1),
        ),
    ]
