# Generated by Django 4.1.5 on 2024-07-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_client_address2_alter_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
