# Generated by Django 4.1.5 on 2024-06-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0002_installmentplan_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
