# Generated by Django 4.1.5 on 2024-06-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_store_sell_price'),
        ('installment', '0004_payment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store'),
        ),
    ]
