# Generated by Django 4.1.5 on 2024-06-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0006_installmentplan_remaining_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentplan',
            name='amount',
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='status',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Активный'), (2, 'Завершенный')], default=0),
        ),
    ]
