# Generated by Django 4.1.5 on 2024-06-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0007_remove_installmentplan_amount_installmentplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
