# Generated by Django 4.1.5 on 2024-07-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0008_alter_installmentproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='installment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='installemt_debt', to='installment.installmentplan'),
            preserve_default=False,
        ),
    ]
