# Generated by Django 4.1.5 on 2024-07-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0009_debt_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
    ]
