# Generated by Django 4.1.5 on 2024-07-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0011_payment_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentplan',
            name='margin_percentage',
        ),
        migrations.RemoveField(
            model_name='installmentplan',
            name='months',
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installment.planmonth'),
        ),
    ]
