# Generated by Django 4.1.5 on 2024-07-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0013_installmentplan_comment_installmentplan_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='status',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Активный'), (2, 'Завершенный'), (4, 'Новый'), (5, 'Заказать')], default=0),
        ),
    ]
