# Generated by Django 4.1.5 on 2024-07-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0014_alter_installmentplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
