# Generated by Django 4.1.5 on 2024-07-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0015_alter_installmentplan_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='remaining_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
