# Generated by Django 4.1.5 on 2024-07-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0016_alter_installmentplan_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='remaining_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
