# Generated by Django 4.1.5 on 2024-07-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0017_alter_installmentplan_next_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='return_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='return_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='status',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Активный'), (2, 'Завершенный'), (4, 'Новый'), (5, 'Заказать'), (6, 'Возврат')], default=0),
        ),
    ]
