# Generated by Django 4.1.5 on 2024-07-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0019_installmentplan_seller_installmentplan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
