# Generated by Django 4.1.5 on 2024-07-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0021_alter_installmentplan_first_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
