# Generated by Django 4.1.5 on 2024-08-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0023_debt_created_at_debt_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='month_str',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='percentage_str',
            field=models.IntegerField(default=0),
        ),
    ]
