# Generated by Django 5.0.4 on 2024-04-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
