# Generated by Django 4.1.5 on 2024-05-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='product_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
