# Generated by Django 4.1.5 on 2024-07-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_brand_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='name_uz',
        ),
    ]
