# Generated by Django 4.1.5 on 2024-07-08 21:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict, null=True), blank=True, default=list, size=None),
        ),
    ]
