# Generated by Django 4.1.5 on 2024-07-29 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_parent_category', to='product.category'),
        ),
    ]
