# Generated by Django 4.1.5 on 2024-05-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_currency_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_main',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
