# Generated by Django 5.0.4 on 2024-04-09 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0002_alter_currency_exchange_rate_and_more'),
        ('product', '0003_color'),
        ('store', '0006_remove_store_swope_swopestore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ram', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('box', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'None'), (1, 'Оплачен'), (2, 'Долг'), (3, 'Долг погашен')], default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.region')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.type')),
            ],
            options={
                'db_table': 'reception',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=200)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.reception')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
