# Generated by Django 5.0.4 on 2024-04-10 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_storeproduct'),
        ('store', '0008_delete_swopehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwopeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_store', to='store.store')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.reception')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_store', to='store.store')),
            ],
            options={
                'db_table': 'swope_history',
                'ordering': ['-id'],
            },
        ),
    ]
