# Generated by Django 5.0.4 on 2024-04-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_remove_swopehistory_reception_swopehistory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='sell',
            field=models.BooleanField(default=False),
        ),
    ]
