# Generated by Django 4.1.5 on 2024-05-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_productcode_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='sell',
            field=models.BooleanField(default=False),
        ),
    ]
