# Generated by Django 4.1.5 on 2024-07-15 20:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0008_storeproduct_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swopehistory',
            old_name='status',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='swopehistory',
            name='count',
        ),
        migrations.AddField(
            model_name='swopehistory',
            name='codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=list, size=None),
        ),
    ]
