# Generated by Django 4.1.5 on 2024-08-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_storebalance_category'),
        ('reception', '0009_rename_status_swopehistory_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store'),
        ),
    ]
