# Generated by Django 4.1.5 on 2024-05-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_price_change',
            field=models.BooleanField(default=False),
        ),
    ]
