# Generated by Django 4.1.5 on 2024-07-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_cashback_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cashback_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
