# Generated by Django 4.1.5 on 2024-08-01 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0009_rename_status_swopehistory_type_and_more'),
        ('order', '0012_alter_order_cashback_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_return_hostory', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_prodcut_return_history', to='reception.storeproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
