# Generated by Django 4.1.5 on 2024-08-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_returnorderhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnorderhistory',
            options={'ordering': ['-id']},
        ),
    ]
